[package]
name = 'usdt'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'git@github.com:aptos-labs/aptos-core.git'
rev = 'conversions'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
admin = '0xf063923ec2831541f3475c795a45e2e074dc150a109c45ac160acc3812ef4cfd'
# BasicCoin = "0xBC"
